// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Okey101.Api.Data;

#nullable disable

namespace Okey101.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327205504_AddGameCenterNameUniqueIndex")]
    partial class AddGameCenterNameUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Okey101.Api.Models.Entities.GameCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("MaxTables")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_GameCenters_Name");

                    b.ToTable("GameCenters");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.GamePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GuestName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameTeamId")
                        .HasDatabaseName("IX_GamePlayers_GameTeamId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_GamePlayers_PlayerId");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Team1FinalTotal")
                        .HasColumnType("int");

                    b.Property<int>("Team2FinalTotal")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WinnerTeamNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByPlayerId")
                        .HasDatabaseName("IX_GameSessions_CreatedByPlayerId");

                    b.HasIndex("TableId")
                        .HasDatabaseName("IX_GameSessions_TableId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.GameTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId")
                        .HasDatabaseName("IX_GameTeams_GameSessionId");

                    b.ToTable("GameTeams");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumberHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumberHash")
                        .HasDatabaseName("IX_OtpCodes_PhoneNumberHash");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumberHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumberHash")
                        .HasDatabaseName("IX_Players_PhoneNumberHash");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_RefreshTokens_PlayerId");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.ScoreEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByPlayerId")
                        .HasDatabaseName("IX_ScoreEntries_CreatedByPlayerId");

                    b.HasIndex("GameSessionId")
                        .HasDatabaseName("IX_ScoreEntries_GameSessionId");

                    b.ToTable("ScoreEntries");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QrCodeIdentifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameCenterId")
                        .HasDatabaseName("IX_Tables_GameCenterId");

                    b.HasIndex("QrCodeIdentifier")
                        .IsUnique()
                        .HasDatabaseName("IX_Tables_QrCodeIdentifier");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.GamePlayer", b =>
                {
                    b.HasOne("Okey101.Api.Models.Entities.GameTeam", "GameTeam")
                        .WithMany("Players")
                        .HasForeignKey("GameTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Okey101.Api.Models.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GameTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.GameSession", b =>
                {
                    b.HasOne("Okey101.Api.Models.Entities.Player", "CreatedByPlayer")
                        .WithMany()
                        .HasForeignKey("CreatedByPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Okey101.Api.Models.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByPlayer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.GameTeam", b =>
                {
                    b.HasOne("Okey101.Api.Models.Entities.GameSession", "GameSession")
                        .WithMany("Teams")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("Okey101.Api.Models.Entities.Player", "Player")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.ScoreEntry", b =>
                {
                    b.HasOne("Okey101.Api.Models.Entities.Player", "CreatedByPlayer")
                        .WithMany()
                        .HasForeignKey("CreatedByPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Okey101.Api.Models.Entities.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByPlayer");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.Table", b =>
                {
                    b.HasOne("Okey101.Api.Models.Entities.GameCenter", "GameCenter")
                        .WithMany()
                        .HasForeignKey("GameCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameCenter");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.GameSession", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.GameTeam", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Okey101.Api.Models.Entities.Player", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
